config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[ index new create destroy ] do
    resources :searches, only: %i[ index show new create destroy ]
  end

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :records, dependent: :destroy
  has_many :users, through: :records
  
  validates :title, presence: true, uniqueness: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, uniqueness: { scope: :user_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :searches, dependent: :destroy
  has_many :records, dependent: :destroy
  has_many :articles, through: :records


  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: %i[ show edit update destroy ]

  # GET /searches or /searches.json
  def index
    @user = User.find(params[:user_id])
    @search = @user.searches.new
    
    if params[:title].present?
      @articles = Article.where("title ILIKE ?","%#{params[:title]}%")
      else
        @articles = Article.all
      end

      if turbo_frame_request?
        render partial: "articles", locals: { articles: @articles }
      else
        render :index
      end
  end

  # GET /searches/1 or /searches/1.json
  def show
    @user = User.find(params[:user_id])
    @search = @user.searches.find(params[:id])
  end

  # GET /searches/new
  def new
    @search = Search.new
    @user = User.find(params[:user_id])
  end

  # POST /searches or /searches.json
  def create
    @user = User.find(params[:user_id])
    @search = @user.searches.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to user_searches_url, notice: "Search was successfully created." }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1 or /searches/1.json
  def destroy
    @search.destroy

    respond_to do |format|
      format.html { redirect_to user_searches_url, notice: "Search was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def search_params
      params.require(:search).permit(:title, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    if params[:username].present?
    @users = User.where("username LIKE ?","%#{params[:username]}%")
    else
    @users = User.all
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_searches_path(@user.id), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpjuiceRailsTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/_form.html.erb
<%= form_with model: [ @user, @user.searches.build ] do |form| %>
  <% if search.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
        <% search.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.label :title, "Title:" %>
    <%= form.text_field :title %>
    <%= form.hidden_field :user_id, value: 1 %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/searches/_search.html.erb
<div id="<%= dom_id search %>">
 <span>
    <%=search.title%>
  </span>
</div>

app/views/searches/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Searches</h1>

<%= form_tag user_searches_path(@user), method: "GET", data: {turbo_frame: "articles", turbo_action: "advance"} do %>
  <%= search_field_tag :title, params[:title]%>
  <%= submit_tag "Search" %>
<% end %>

<div id="searches">
  <% @articles.each do |article| %>
  <div>
    <%= article.title %>
    </div>
  <% end %>
</div>

<%= link_to "New search", new_user_search_path %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render "form", search: @search %>

<br>

<div>
  <%= link_to "Back to searches", user_searches_path %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :username, "Username:" %>
  <%= form.text_field :username %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <%= link_to user.username, user_searches_path(user) %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Username</h1>

<%= form_tag "/users", method: "GET" do %>
  <%= search_field_tag :username, params[:username]%>
  <%= submit_tag "Search" %>
<% end %>

<div id="users">
  <% @users.each do |user| %>
  <%= render user %>
    
    <p>
      <%= button_to "delete", user, method: :delete %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>